### Register a User
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "name": "Test User"
}

###

### Login a User
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "rafli@gmail.com",
  "password": "password123"
}

###

### Create a Blog
POST http://localhost:5000/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "content": "This is a test blog.",
  "authorId": 1
}


### Get All Blogs
GET http://localhost:5000/blogs
Content-Type: application/json

###

### Get a Single Blog by ID
GET http://localhost:5000/blogs/1
Content-Type: application/json

###

### Update a Blog
PUT http://localhost:5000/blogs/1
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "title": "Updated Test Blog",
  "content": "This is an updated test blog.",
  "image": "https://example.com/image.png"
}

###

### Delete a Blog
DELETE http://localhost:5000/blogs/1
Content-Type: application/json
# Authorization: Bearer {{token}}

###

### Get Profile
GET http://localhost:5000/profile
Content-Type: application/json
# Authorization: Bearer {{token}}

###

### Create Profile
POST http://localhost:5000/profile
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "fullName": "Test User",
  "address": "123 Test St",
  "image": "https://example.com/image.png",
  "userId": 1
}

###

### Update Profile
PUT http://localhost:5000/profile/1
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "fullName": "Updated Test User",
  "address": "123 Updated Test St",
  "image": "https://example.com/updated-image.png"
}

###

### Delete Profile
DELETE http://localhost:5000/profile/1
Content-Type: application/json
# Authorization: Bearer {{token}}
