### Create User
POST http://localhost:5000/auth/register
Content-Type: application/json

{ "fullName" : "rafli",
  "email": "user@example.com",
  "password": "password123",
  "role" : "user",
}


### Get All Users
GET http://localhost:5000/api/users
Content-Type: application/json

### Get User by ID
GET http://localhost:5000/users/1
Content-Type: application/json

### Update User
PUT http://localhost:5000/users/1
Content-Type: application/json

{
  "email": "john.updated@example.com",
  "name": "John Updated",
  "role": "user"
}

### Delete User
DELETE http://localhost:5000/users/1
Content-Type: application/json

### Create or Update Profile
POST http://localhost:5000/api/profiles/
Content-Type: application/json

{
  "fullName": "rafli",
  "address": "123 Main St",
  "image": "http://example.com/image.jpg",
  
}
### GET
GET http://localhost:5000/api/profiles/
Content-Type: application/json

### Membuat profil baru
POST http://localhost:5000/api/profiles
Content-Type: multipart/form-data


{
  
}



### Get Profile by User ID
GET http://localhost:5000/admin/profiles
Content-Type: application/json

### Create Blog
POST http://localhost:5000/api/blogs
Content-Type: application/json

{
  "title": "My First Blog",
  "content": "This is the content of my first blog.",
  "image": "http://example.com/blog-image.jpg",
  "authorId": 45
}

### Get All Blogs
GET http://localhost:5000/api/blogs
Content-Type: application/json

### Get Blog by ID
GET http://localhost:5000/blogs/1
Content-Type: application/json

### Update Blog
PUT http://localhost:5000/blogs/1
Content-Type: application/json

{
  "title": "Updated Blog Title",
  "content": "This is the updated content of the blog.",
  "image": "http://example.com/updated-blog-image.jpg"
}

### Delete Blog
DELETE http://localhost:5000/blogs/1
Content-Type: application/json
